name: polyprotein-assembler
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - nextflow>=21.04.0
  - openjdk>=11.0.0
  
  # Quality control and trimming
  - fastqc=0.11.9
  - trimmomatic=0.39
  
  # Assembly
  - megahit=1.2.9
  - spades=3.15.5
  
  # Sequence manipulation
  - emboss=6.6.0
  - biopython=1.79
  - seqtk=1.3
  
  # HMM search
  - hmmer=3.3.2
  
  # Mapping and BAM manipulation
  - bwa=0.7.17
  - samtools=1.15
  
  # Data analysis and visualization
  - pandas=1.4.3
  - matplotlib=3.5.2
  - networkx=2.8.4
  
  # Alignment tools
  - mafft=7.490
  - muscle=5.1
  
  # Sequence clustering
  - cd-hit=4.8.1
  
  # Python packages not available in bioconda/conda-forge
  - pip
  - pip:
    - pyhmmer==0.7.0  # Native Python HMMER library with ARM64 support

# Notes on Apple Silicon compatibility:
# This environment file is optimized for Apple Silicon (M1/M2/M3) Macs.
# When installing, use:
#   CONDA_SUBDIR=osx-arm64 conda env create -f conda/conda-apple-silicon.yml